[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.update]
command = "cargo"
args = ["update"]

[tasks.format]
toolchain = "nightly"

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["update"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--", "--no-deps"]

[tasks.bench]
command = "cargo"
args = ["bench"]
dependencies = ["update"]

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
